- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 1h
    inverted: false # floofstation - let people choose how they want to play their character
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  canBeAntag: true # DeltaV - Can be antagonist
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ResearchAssistantGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
    pocket2: BookScientistsGuidebook
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ResearchAssistantChameleonOutfit
  job: ResearchAssistant
  equipment:
    head: ClothingHeadHatCardborg
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
